title: 萬華阿嗚人力資源經紀
e-mail: sole.preload-4l@icloud.com
description: "臺北市、新北市、基隆市、桃園市，臨時工、短期人力、長期駐點等，人力資源中介服務。"
baseurl: ""
url: "bobojayjay.github.io"
markdown: kramdown
theme: jekyll-theme-so-simple
jekyll_theme_so_simple_skin: dark
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"